name: publish
run-name: Publish to Github Package Registry

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Publish to Github Package Registry
        run: |
           echo "@akalanka47000:registry=https://npm.pkg.github.com" >> .npmrc
           echo "//npm.pkg.github.com/:_authToken=${{ secrets.REGISTRY_ACCESS_TOKEN }}" >> .npmrc
           npm publish
